import Header from "@/components/Header/Header";
import "./globals.css";
import "@/styles/header.css";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import ThemeContextProvider from "@/Contexts/ThemeContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        {/* <ThemeContextProvider> */}
        <ThemeRegistry options={{ key: "mui" }}>
          <Header />
          {children}
        </ThemeRegistry>
        {/* </ThemeContextProvider> */}
      </body>
    </html>
  );
}
